// Generated by CoffeeScript 1.3.1
var app, db, io, server;

app = require('express')();

server = require('http').createServer(app);

io = require('socket.io').listen(server);

db = require('nano')('http://192.168.1.188:5984/novel');

server.listen(18080);

app.get('/', function(req, res) {
  return res.sendfile(__dirname + '/index.html');
});

io.sockets.on('connection', function(socket) {
  return db.view('index', 'books', {
    group: true
  }, function(err, body) {
    console.log("body:::");
    console.log(body);
    return socket.emit('index', body.rows);
  });
});

io.sockets.on('message', function(message, callback) {
  console.log(message);
  return socket.emit('message', {
    ping: 'server'
  });
});

io.sockets.on('disconnect', function() {
  return console.log('client disconnected');
});
