// Generated by CoffeeScript 1.3.1
var app, io, server;

app = require('express')();

server = require('http').createServer(app);

io = require('socket.io').listen(server);

server.listen(18080);

app.get('/', function(req, res) {
  return res.sendfile(__dirname + '/index.html');
});

io.sockets.on('connection', function(socket) {
  socket.emit('message', {
    ping: 'server'
  });
  return socket.on('my other event', function(data) {
    return console.log(data);
  });
});

io.sockets.on('message', function(message, callback) {
  console.log(message);
  return socket.emit('message', {
    ping: 'server'
  });
});

io.sockets.on('disconnect', function() {
  return console.log('disconnect');
});
